apiVersion: v1
kind: Service
metadata:
    labels:
        service: udaconnect-location-ingestion-service
    name: udaconnect-location-ingestion-service
spec:
    ports:
        - name: "5003"
          port: 5003
          targetPort: 5003
          nodePort: 30008
    selector:
        service: udaconnect-location-ingestion-service
    type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        service: udaconnect-location-ingestion-service
    name: udaconnect-location-ingestion-service
spec:
    replicas: 1
    selector:
        matchLabels:
            service: udaconnect-location-ingestion-service
    template:
        metadata:
            labels:
                service: udaconnect-location-ingestion-service
        spec:
            containers:
                - image: arfatmateen/udaconnect-location-ingestion-service:latest
                  name: udaconnect-location-ingestion-service
                  imagePullPolicy: Always
                  env:
                      - name: DB_USERNAME
                        valueFrom:
                            configMapKeyRef:
                                name: db-env
                                key: DB_USERNAME
                      - name: DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: db-secret
                                key: DB_PASSWORD
                      - name: DB_NAME
                        valueFrom:
                            configMapKeyRef:
                                name: db-env
                                key: DB_NAME
                      - name: DB_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: db-env
                                key: DB_HOST
                      - name: DB_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: db-env
                                key: DB_PORT
            restartPolicy: Always
