apiVersion: v1
kind: Service
metadata:
    labels:
        service: udaconnect-location-generator-service
    name: udaconnect-location-generator-service
spec:
    ports:
        - name: "5001"
          port: 5001
          targetPort: 5001
          nodePort: 30007
    selector:
        service: udaconnect-location-generator-service
    type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        service: udaconnect-location-generator-service
    name: udaconnect-location-generator-service
spec:
    replicas: 1
    selector:
        matchLabels:
            service: udaconnect-location-generator-service
    template:
        metadata:
            labels:
                service: udaconnect-location-generator-service
        spec:
            containers:
                - image: arfatmateen/udaconnect-location-generator-service:latest
                  name: udaconnect-location-generator-service
                  imagePullPolicy: Always
            restartPolicy: Always
